version: '3'
services:
  react:
    container_name: reactjs
    image: postgres:14
    ports:
      - "8898:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres